// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq3kr_M4AOioan_OzeWBzA-5AwXMVo-Rk',
    appId: '1:239467616339:web:823cc9d29cd92f3ae74ea6',
    messagingSenderId: '239467616339',
    projectId: 'eventos-teste-16301',
    authDomain: 'eventos-teste-16301.firebaseapp.com',
    storageBucket: 'eventos-teste-16301.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNSHIMVRyVOIe3eFijZEF02_DCCIeLTsU',
    appId: '1:239467616339:android:36cc2a854899db00e74ea6',
    messagingSenderId: '239467616339',
    projectId: 'eventos-teste-16301',
    storageBucket: 'eventos-teste-16301.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGk-1j3-KI-edEn_Jthn-Jr7zcRD9JgFY',
    appId: '1:239467616339:ios:c269970e37331c62e74ea6',
    messagingSenderId: '239467616339',
    projectId: 'eventos-teste-16301',
    storageBucket: 'eventos-teste-16301.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGk-1j3-KI-edEn_Jthn-Jr7zcRD9JgFY',
    appId: '1:239467616339:ios:c269970e37331c62e74ea6',
    messagingSenderId: '239467616339',
    projectId: 'eventos-teste-16301',
    storageBucket: 'eventos-teste-16301.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq3kr_M4AOioan_OzeWBzA-5AwXMVo-Rk',
    appId: '1:239467616339:web:8b17e41cff5fc145e74ea6',
    messagingSenderId: '239467616339',
    projectId: 'eventos-teste-16301',
    authDomain: 'eventos-teste-16301.firebaseapp.com',
    storageBucket: 'eventos-teste-16301.firebasestorage.app',
  );
}
